apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml --volumes hostPath
    kompose.image-pull-policy: Never
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: balance
  name: balance
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: balance
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml --volumes hostPath
        kompose.image-pull-policy: Never
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: balance
    spec:
      containers:
        - image: java-balance:latest
          imagePullPolicy: Never
          name: bankaccount-balance
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
